### ISSUE TITLE
Cuda 11.4.2 issues on Summit

### ISSUE THREAD

**Issue by tasmith4** [sandialabs/spack-manager#276]
@ldh4 and I have noticed that the latest Trilinos develop doesn't build with the latest spack-manager on Summit, with a build error like this:
```
  >> 2038    /autofs/nccs-svm1_home1/tasmit/exawind/sources/trilinos/packages/stk/stk_unit_test_utils/stk_unit_test_utils/TextMeshDataTypes.hpp:213:14: error
             : '__T0' was not declared in this scope; did you mean '__y0'?
     2039      213 |     auto it(m_nodalCoords.find(nodeId));
     2040          |         ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~
     2041          |         __y0
```

This seems like a cuda version-specific issue, especially since the same Trilinos built successfully for us under Cuda 11.0.3.

@jrood-nrel I noticed you had bumped the default cuda to 11.4.2 a couple weeks ago in 
#269 -- can you reproduce this build error?  If so, maybe we should go back to 11.0.3?

cc @psakievich

**Comment by jrood-nrel** [comment]
We've been building with cuda 11.4.2 on Summit. This is what Paul is using. I see this error as well. This is a regression.

**Comment by tasmith4** [comment]
@jrood-nrel just to clarify so you're saying this is a regression in Trilinos (specifically STK) -- i.e. it was working before and now is not with cuda 11.4.2?

What are your thoughts on the best path forward here?  I'm unsure because normally I would say, fix the bug in the code, but this is completely valid C++ as far as I can tell, and the weird symbols in the error message seem to indicate that the new STK code has tripped some latent bug in this cuda version.

Based on that, I lean toward thinking we should either upgrade or downgrade our default cuda version on summit to avoid this bug, but I'd like to hear your thoughts as well.

**Comment by jrood-nrel** [comment]
To answer your first question: yes

Paul has succeeded running our largest simulation yet of 4 turbines in which he was using CUDA 11.4.2 on Summit. I have no idea if that was crucial to success but I think that should be the version we want to use at the moment because of this feat. I don't think we should move backwards. Paul suggests commit `0bbbbe2518c278bfc0e0a44d4c771c952c2f7633`. I'm guessing there are other instances where code was manipulated to workaround a compiler. We do it in the exawind-driver for CUDA because sometimes it can't parse legitimate C++.

**Comment by jrood-nrel** [comment]
https://github.com/Exawind/exawind-driver/pull/11

**Comment by tasmith4** [comment]
@jrood-nrel we found the correct workaround and confirmed it fixes the build issues in a one-off Summit build with Cuda 11.4.2.  I'll leave this issue open until the fix makes it into trilinos@develop.

**Comment by tasmith4** [comment]
The fix is in
